### ISSUE TITLE
some POP3 tests are inconsistent WRT CRAM-MD5 offering and fake_mail_server support

### ISSUE THREAD

**Issue by mandree** [FHMS-ITS/EAST#3]
Greetings, and thanks for providing a large set of tests.

Toying around with the POP3 tests, I find that many offer, in response to a CAPA reqeuest, a SASL CRAM-MD5 ... response, yet do not implement CRAM-MD5. Some clients then send AUTH CRAM-MD5 but the fake_mail_server does not implement this and refuses the client and ends the conversation. 

I haven't had time to look deeper if you want to check any more details from the tests afterwards but would already conclude that the POP3 test cases should not offer CRAM-MD5 in their CAPA responses.

**Comment by duesee** [comment]
Hello, when your client is configured to enforce the transition to TLS and it proceeds with CRAM-MD5 in plaintext instead, this is a security issue. At one point we just added all AUTH mechanisms we could identify to test if any is accepted. Which client are you using in which configuration?

**Comment by mandree** [comment]
I am not disclosing client information now since the implications need to be coordinated with the client's vendor first.

What happens is that the client sends STARTTLS, the server accepts it, both complete the TLS handshake, the client sends (in POP3) AUTH CRAM-MD5 and then fake-mail-server refuses (replies with -ERR) and aborts the connection. This is with `testcases/pop3/Buffering/B_1.ron`.  Trace below.  Let me know if there's anything fishy _except the server prematurely dropping the hook^Wconnection_.

```
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | S: +OK POP3 server ready.\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | C: CAPA\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | S: +OK list of capabilities\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. STLS\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. TOP\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. USER\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. SASL CRAM-MD5 KERBEROS_V4\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. RESP-CODES\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. LOGIN-DELAY 900\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. PIPELINING\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. EXPIRE 60\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. UIDL\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. IMPLEMENTATION fake_mail_server\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. .\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | C: STLS\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | S: +OK Begin fake TLS negotiation now.\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | <----- TLS handshake ----->
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | C: CAPA\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | S: +OK list of capabilities\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. TOP\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. USER\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. SASL CRAM-MD5 KERBEROS_V4\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. RESP-CODES\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. LOGIN-DELAY 900\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. PIPELINING\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. EXPIRE 60\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. UIDL\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. IMPLEMENTATION fake_mail_server\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | .. .\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | C: AUTH CRAM-MD5\r\n
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | {"message": "not supported", "mechanism": "cram-md5"}
testcases/pop3/Buffering/B_1.ron ("undisclosed") > WeneHgSz | S: -ERR not supported.\r\n
<Press ENTER to continue>
```

The client would attempt a regular LOGIN later if the server wasn't dropping the hook... (tried by excluding CRAM-MD5 from the fake SASL response, and by blocking CRAM-MD5 in the client and forcing USER/PASS login). If there are clients that blindly send CRAM-MD5 then I would suggest that fake-email-server at least remains online after refusing the SASL method it advertised earlier.

I should maybe mention that the client *does* validate the certificate (and I gave it a real one for my server where I am my own CA, not just some fake stuff) and would kill the connection if the TLS handshake were somehow fishy. BTDT, and I couldn't get the client to accept the mkcert output (wrong CN..., but I didn't try hard but just switched to "real" X.509 stuff.)

**Comment by duesee** [comment]
>  Trace below. Let me know if there's anything fishy except the server prematurely dropping the hook^Wconnection.

The B_* tests require manual editing of the test files for now. Your trace looks fine, but the response injection is not tested.

To test for the response injection in your specific client, which sends CAPA as the first command after the TLS handshake, you could edit the B_1.ron file as follows:

```
(
    greeting: "+OK POP3 server ready.\r\n",

    capa: ["STLS", "TOP", "USER", "SASL CRAM-MD5 KERBEROS_V4", "RESP-CODES", "LOGIN-DELAY 900", "PIPELINING", "EXPIRE 60", "UIDL", "IMPLEMENTATION fake_mail_server"],
    capa_auth: ["TOP", "USER", "SASL CRAM-MD5 KERBEROS_V4", "RESP-CODES", "LOGIN-DELAY 900", "PIPELINING", "EXPIRE 60", "UIDL", "IMPLEMENTATION fake_mail_server"],
    capa_tls: ["TOP", "USER", "SASL CRAM-MD5 KERBEROS_V4", "RESP-CODES", "LOGIN-DELAY 900", "PIPELINING", "EXPIRE 60", "UIDL", "IMPLEMENTATION fake_mail_server"],
    capa_tls_auth: ["TOP", "USER", "SASL CRAM-MD5 KERBEROS_V4", "RESP-CODES", "LOGIN-DELAY 900", "PIPELINING", "EXPIRE 60", "UIDL", "IMPLEMENTATION fake_mail_server"],

    // 1) What is the first command after STLS the client issues?

    // 2) If you know the command, uncomment the following line and see if the client waits for it.
    // (Example "auth" is based on Thunderbirds behaviour.)
    ignore_commands_tls: ["capa"], // EDITED

    // 2) Evaluate if answer to the command can be injected in plaintext.
    // Uncomment the following line and see if client proceeds now.
    stls_response: "+OK Begin fake TLS negotiation now.\r\n+OK list of capabilities\r\n", // EDITED

    pkcs12: (
        file: "certs/example.org.p12",
        password: "changeit",
    ),
    implicit_tls: false,
)
```

Feel free to provide the trace again so that we can evaluate it together. (We plan to automate the tests for the response injection eventually, but didn't had the time to do so.)

**Comment by mandree** [comment]
Yeah, the interim internal (unreleased) version of the client and the edited B_1.ron with its changed stls_response can't chat properly:

I interpret it such that the excess data `+OK list of capabilities\r\n` now jams the TLS negotiation. The original B_1.ron response apparently somehow doesn't choke OpenSSL. Whatever.

```
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | S: +OK POP3 server ready.\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | C: CAPA\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | S: +OK list of capabilities\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. STLS\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. TOP\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. USER\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. SASL CRAM-MD5 KERBEROS_V4\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. RESP-CODES\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. LOGIN-DELAY 900\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. PIPELINING\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. EXPIRE 60\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. UIDL\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. IMPLEMENTATION fake_mail_server\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. .\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | C: STLS\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | S: +OK Begin fake TLS negotiation now.\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | .. +OK list of capabilities\r\n
testcases/pop3/Buffering/B_1.ron ("client") > 5IqfVS1p | <----- TLS handshake ----->
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Ssl(Error { code: ErrorCode(5), cause: Some(Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })) }, X509VerifyResult { code: 0, error: "ok" })', src/lib.rs:313:86
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and the fixed client sends STLS, sees the +OK line, tries SSLOpen() and then logs an OpenSSL error: `error:1408F10B:SSL routines:ssl3_get_record:wrong version number`. The client logs a failed TLS upgrade, and drops the connection. 

Looks safe to me, but still the test case should not offer CRAM-MD5 unless fake_email_server supports it...

**Comment by duesee** [comment]
> Looks safe to me, but still the test case should not offer CRAM-MD5 unless fake_email_server supports it...

Agree. I will fix it (either by implementing CRAM-MD5) or by removing the caps.

**Comment by duesee** [comment]
I will close this issue now, please open any new issues in the respective repositories in https://github.com/Email-Analysis-Toolkit. (We separated the tools for easier maintenance, but will keep the FHMS-ITS/EAST repository as a landing page.
