### ISSUE TITLE
Problem running "imap/Negotiation/O_1.ron

### ISSUE THREAD

**Issue by bloppydrago** [FHMS-ITS/EAST#5]
Hihi there seems to be an issue with the Auth(Other(...)). When I run it there is an error saying Expected struct.

<img width="842" alt="Screenshot 2021-09-20 102608" src="https://user-images.githubusercontent.com/91040389/134099123-4091b24f-01cc-421b-8df4-129c0598791e.png">

**Comment by duesee** [comment]
Hey, this error seems to be very similar to the one you reported yesterday. Could you try to wrap the String in an `Atom("...")`? Would be awesome if you could try that or even send a pull request? :-)

Otherwise I can try to fix that tomorrow :-)

**Comment by Murgeye** [comment]
Hi,

This is a new testcase, right? O_1 doesn't have this for me.

Try

```
code: Some(Capability([Imap4Rev1, Auth(Plain), Auth(Login), Auth(Other(Atom("EXTERNAL")))])),
```

instead. Without the `Atom` the imap codec does not know which kind of data is given.

And please, put any issues for the fake mail server into the fake mail server repository in the future:
https://github.com/Email-Analysis-Toolkit/fake-mail-server

Best,
Fabian

**Comment by bloppydrago** [comment]
@duesee and @Murgeye thanks for your help it works now. If there is any more issues I will put it into the fake mail server repo :)

**Comment by duesee** [comment]
Let me keep this open to not forget to fix the comments. Will do so tomorrow, thanks for the report!

**Comment by duesee** [comment]
Fixed in https://github.com/Email-Analysis-Toolkit/fake-mail-server/commit/c21fcb797be6454676567e4707cabe518350712e
